### ISSUE TITLE
listener example doesn't work

### ISSUE THREAD

**Issue by marnixbent** [d0whc3r/bittrex-api#1]
Hi,

When i'm copy-pasting your listener example, no ticker updates are logged to the console. Am I missing something?

Thanks in advance

**Comment by d0whc3r** [comment]
"bittrex.websockets.listen" is not working because bittrex removed websocket listen method.
You could use "bittrex.websockets.subscribe" and this returns a promise with argument "wsclient" which is the socket client

PD: Examples are not working because they are from forked repository

**Comment by marnixbent** [comment]
Thanks!

**Comment by slidenerd** [comment]
You should eliminate the signal r client,it has a timeout leak which you ll find if you search "CPU" on their issues, my CPU usage spiked to 100% when I installed the node-bittrex-api which uses signal r underlying

**Comment by slidenerd** [comment]
Apologies just tested your library, for some reason i get that CPU spike if I use https://github.com/dparlevliet/node.bittrex.api
